server:
  port: 8888
  servlet:
    context-path: /spring_boot

#food: kfc  #(KV)
#student:
#  name: admin
#  age: 12
#  sex: man
#
#city:
#  - wuhan
#  - tianjing
#  - beijing
#
#city1: [wuhan,nanjing]
#teacher:
#  - name: Miss Wang
#    age: 24
#    sex: woman
#  - name: Join
#    age: 25
#    sex: man
#
#spring:
#  datasource:
#    username: root
#    password: root
spring:
  datasource:
    username: akifui
    password: 2672322655@qq.COM
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.170.32:3306/spring_boot
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 4
      max-active: 10
      max-wait: 6000
      # Druid性能统计监控的核心配置  stat配置Druid数据源的监控和性能统计 wall配置Druid连接池的防火墙 log4j配置Druid连接池的日志
      filters: stat,wall,log4j
      # 开启PreparedStatements Cache(提升写入、查询效率)，MySQL5.7以上建议true
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  freemarker:
    allow-request-override: false  #是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-session-override: false  #是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
    cache: false  #是否启用模板缓存。
    charset: utf-8  #编码方式
    check-template-location: true  #是否检查模板位置是否存在
    content-type: text/html  #Content-Type value.
    enabled: true  #是否启用freemarker
    expose-request-attributes: false  #设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-session-attributes: false  #是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-spring-macro-helpers: true  #设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    prefer-file-system-access: true  #是否优先从文件系统加载template，以支持热加载，默认为true
    suffix: .ftl  #设定模板的后缀.
    template-loader-path: classpath:/templates/  #文件路径
    settings:
      template_update_delay: 0
      .default_encoding: UTF-8
      classic_compatible: true
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload/
#  mvc:
#    static-path-pattern: /static/**
  #文件上传下载容量
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.blessingsoftware.entity
